improve mkproj

diff --git a/mkproj b/mkproj
--- a/mkproj
+++ b/mkproj
@@ -1,19 +1,19 @@
 #!/usr/bin/env bash
 
-set -Eeuo pipefail
-
 projname="$1"
 if [[ -z "$projname" ]]; then
 	echo "usage: $(basename "$0") <project-name>"
 	exit 1
 fi
-if [[ -e "$projname" ]]; then
+if [[ -d "$projname" ]]; then
+	echo "Error: $projname is a directory."
+	exit 1
+elif [[ -f "$projname" ]]; then
 	read -rp "$projname already exists. Overwrite? (y/n): " choice
 	[[ "$choice" =~ ^[yY]([eE][sS])?$ ]] || exit 0
 fi
 cat <<EOF > "$projname"
 #!/usr/bin/env bash
-set -Eeuo pipefail
 EOF
 chmod +x "$projname"
 echo "Successfully initialized $projname."
