Improve weather script

diff --git a/weather b/weather
--- a/weather
+++ b/weather
@@ -2,11 +2,18 @@
 
 set -Eeuo pipefail
 
-CITY="${1:-${CITY:-Englewood}}"
+CITY="${*:-${CITY:-}}"
+if [[ -z "$CITY" ]]; then
+	echo "Error: No city specified."
+	echo "Usage: $0 <city name> OR set the CITY environment variable."
+	exit 1
+fi
 UNIT_TYPE="${UNITS:-F}"
 URL_CITY="${CITY// /+}"
-
 weather_data=$(curl -sf "https://wttr.in/${URL_CITY}?format=j1")
+area=$(echo "$weather_data" | jq -r '.nearest_area[0].areaName[0].value')
+region=$(echo "$weather_data" | jq -r '.nearest_area[0].region[0].value')
+country=$(echo "$weather_data" | jq -r '.nearest_area[0].country[0].value')
 if [[ "${UNIT_TYPE^^}" == "C" ]]; then
 	temp=$(echo "$weather_data" | jq -r '.current_condition[0].temp_C')
 	feels_like=$(echo "$weather_data" | jq -r '.current_condition[0].FeelsLikeC')
@@ -17,6 +24,6 @@ else
 	unit_label="F"
 fi
 condition=$(echo "$weather_data" | jq -r '.current_condition[0].weatherDesc[0].value')
-echo "Current weather for ${CITY}:"
-echo "Condition: $condition."
-echo "Temperature: ${temp}${unit_label}; feels like ${feels_like}${unit_label}."
+echo "Current weather for $area, $region, $country:"
+echo "Condition: $condition"
+echo "Temperature: ${temp}${unit_label} (Feels like: ${feels_like}${unit_label})"
